language: python
sudo: False
matrix:
    include:
        - python: "2.7" 
        #- python: "3.5"
        #  env: SKLEARN="0.18.1"
        #- python: "3.4" 
        #  env: SKLEARN="0.18.1"

# setup adapted from https://github.com/soft-matter/trackpy/blob/master/.travis.yml
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
    - conda update --yes conda
    - conda info -a

install: 
    - conda install --yes nose python=${TRAVIS_PYTHON_VERSION}
    - which python
    - python setup.py install
    - pwd

script: 
    - which nosetests
    - nosetests -sv test

#after_success:
#    coveralls

