language: python
sudo: False
matrix:
    include:
        - python: "3.5"
        - python: "2.7" 

# setup adapted from https://github.com/soft-matter/trackpy/blob/master/.travis.yml
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
    - conda update --yes conda
    - conda info -a

install: 
    - conda install --yes nose python=${TRAVIS_PYTHON_VERSION}
    - python setup.py install

script: 
    - nosetests -sv test

#after_success:
#    coveralls

